#ifndef PART_MACRO
    #define PART_MACRO(name, type, cache) class name;
    #define PART_MACRO_EPHEMERAL
#endif

PART_MACRO(PBody, PART_TYPE_BODY, PART_CACHE_INVALID)
PART_MACRO(PJoint, PART_TYPE_JOINT, PART_CACHE_JOINT)
PART_MACRO(PWorld, PART_TYPE_WORLD, PART_CACHE_WORLD)
PART_MACRO(PRenderMesh, PART_TYPE_RENDER_MESH, PART_CACHE_INVALID)
PART_MACRO(PPos, PART_TYPE_POS, PART_CACHE_INVALID)
PART_MACRO(PTrigger, PART_TYPE_TRIGGER, PART_CACHE_TRIGGER)
PART_MACRO(PYellowHead, PART_TYPE_YELLOW_HEAD, PART_CACHE_YELLOW_HEAD)
PART_MACRO(PAudioWorld, PART_TYPE_AUDIO_WORLD, PART_CACHE_AUDIO_WORLD)
PART_MACRO(PAnimation, PART_TYPE_ANIMATION, PART_CACHE_INVALID)
PART_MACRO(PGeneratedMesh, PART_TYPE_GENERATED_MESH, PART_CACHE_GENERATED_MESH)
PART_MACRO(PLevelSettings, PART_TYPE_LEVEL_SETTINGS, PART_CACHE_INVALID)
PART_MACRO(PSpriteLight, PART_TYPE_SPRITE_LIGHT, PART_CACHE_SPRITE_LIGHT)
PART_MACRO(PScriptName, PART_TYPE_SCRIPT_NAME, PART_CACHE_SCRIPT_NAME)
PART_MACRO(PCreature, PART_TYPE_CREATURE, PART_CACHE_CREATURE)
PART_MACRO(PCheckpoint, PART_TYPE_CHECKPOINT, PART_CACHE_INVALID)
PART_MACRO(PStickers, PART_TYPE_STICKERS, PART_CACHE_STICKERS)
PART_MACRO(PDecorations, PART_TYPE_DECORATIONS, PART_CACHE_DECORATIONS)
PART_MACRO(PScript, PART_TYPE_SCRIPT, PART_CACHE_SCRIPT)
PART_MACRO(PShape, PART_TYPE_SHAPE, PART_CACHE_INVALID)
PART_MACRO(PEffector, PART_TYPE_EFFECTOR, PART_CACHE_INVALID)
PART_MACRO(PEmitter, PART_TYPE_EMITTER, PART_CACHE_EMITTER)
PART_MACRO(PRef, PART_TYPE_REF, PART_CACHE_INVALID)
PART_MACRO(PMetaData, PART_TYPE_META_DATA, PART_CACHE_INVALID)
PART_MACRO(PCostume, PART_TYPE_COSTUME, PART_CACHE_COSTUME)
PART_MACRO(PCameraTweak, PART_TYPE_CAMERA_TWEAK, PART_CACHE_CAMERA_TWEAK)
PART_MACRO(PSwitch, PART_TYPE_SWITCH, PART_CACHE_SWITCH)
PART_MACRO(PSwitchKey, PART_TYPE_SWITCH_KEY, PART_CACHE_SWITCH_KEY)
PART_MACRO(PGameplayData, PART_TYPE_GAMEPLAY_DATA, PART_CACHE_GAMEPLAY_DATA)
PART_MACRO(PEnemy, PART_TYPE_ENEMY, PART_CACHE_ENEMY)
PART_MACRO(PGroup, PART_TYPE_GROUP, PART_CACHE_GROUP)
PART_MACRO(PPhysicsTweak, PART_TYPE_PHYSICS_TWEAK, PART_CACHE_PHYSICS_TWEAK)
#ifndef LBP1
PART_MACRO(PNpc, PART_TYPE_NPC, PART_CACHE_NPC)
PART_MACRO(PSwitchInput, PART_TYPE_SWITCH_INPUT, PART_CACHE_SWITCH_INPUT)
PART_MACRO(PMicroChip, PART_TYPE_MICROCHIP, PART_CACHE_MICROCHIP)
PART_MACRO(PMaterialTweak, PART_TYPE_MATERIAL_TWEAK, PART_CACHE_MATERIAL_TWEAK)
PART_MACRO(PMaterialOverride, PART_TYPE_MATERIAL_OVERRIDE, PART_CACHE_INVALID)
PART_MACRO(PInstrument, PART_TYPE_INSTRUMENT, PART_CACHE_INVALID)
PART_MACRO(PSequencer, PART_TYPE_SEQUENCER, PART_CACHE_INVALID)
PART_MACRO(PControlinator, PART_TYPE_CONTROLINATOR, PART_CACHE_INVALID)
#endif
#if defined(LBP3) || defined(HAS_CROSS_CONTROLLER)
PART_MACRO(PPoppetPowerup, PART_TYPE_POPPET_POWERUP, PART_CACHE_INVALID)
PART_MACRO(PPocketItem, PART_TYPE_POCKET_ITEM, PART_CACHE_INVALID)
PART_MACRO(PTransition, PART_TYPE_TRANSITION, PART_CACHE_INVALID)
PART_MACRO(PFader, PART_TYPE_FADER, PART_CACHE_INVALID)
PART_MACRO(PAnimationTweak, PART_TYPE_ANIMATION_TWEAK, PART_CACHE_ANIMATION_TWEAK)
PART_MACRO(PWindTweak, PART_TYPE_WIND_TWEAK, PART_CACHE_WIND_TWEAK)
PART_MACRO(PPowerUp, PART_TYPE_POWER_UP, PART_CACHE_INVALID)
PART_MACRO(PTagSynchronizer, PART_TYPE_TAG_SYNCHRONIZER, PART_CACHE_INVALID)
PART_MACRO(PWormhole, PART_TYPE_WORMHOLE, PART_CACHE_INVALID)
PART_MACRO(PQuest, PART_TYPE_QUEST, PART_CACHE_INVALID)
PART_MACRO(PConnectorHook, PART_TYPE_CONNECTOR_HOOK, PART_CACHE_INVALID)
PART_MACRO(PAtmosphericTweak, PART_TYPE_ATMOSPHERIC_TWEAK, PART_CACHE_ATMOSPHERIC_TWEAK)
PART_MACRO(PStreamingData, PART_TYPE_STREAMING_DATA, PART_CACHE_STREAMING_DATA)
PART_MACRO(PStreamingHint, PART_TYPE_STREAMING_HINT, PART_CACHE_INVALID)
#endif

#ifdef PART_MACRO_EPHEMERAL
    #undef PART_MACRO
    #undef PART_MACRO_EPHEMERAL
#endif
