#pragma once

#include "Part.h"

enum ESwitchType
{
	SWITCH_TYPE_INVALID = -1,
	SWITCH_TYPE_BUTTON = 0,
	SWITCH_TYPE_LEVER = 1,
	SWITCH_TYPE_TRINARY = 2,
	SWITCH_TYPE_PROXIMITY = 3,
	SWITCH_TYPE_KEY = 4,
	SWITCH_TYPE_STICKER = 5,
	SWITCH_TYPE_GRAB = 6,
	SWITCH_TYPE_PRESSURE = 7,
	SWITCH_TYPE_PAINT = 8,
	SWITCH_TYPE_CONTROLLER_BINARY = 9,
	SWITCH_TYPE_CONTROLLER_ANALOG = 10,
	SWITCH_TYPE_SACKBOT_KEY = 11,
	SWITCH_TYPE_SACKBOT_PLAYER = 12,
	SWITCH_TYPE_SACKBOT_BOT = 13,
	SWITCH_TYPE_AND = 14,
	SWITCH_TYPE_COUNTDOWN = 15,
	SWITCH_TYPE_TIMER = 16,
	SWITCH_TYPE_TOGGLE = 17,
	SWITCH_TYPE_IMPACT = 18,
	SWITCH_TYPE_RANDOM = 19,
	SWITCH_TYPE_DIRECTION = 20,
	SWITCH_TYPE_OR = 21,
	SWITCH_TYPE_XOR = 22,
	SWITCH_TYPE_NOT = 23,
	SWITCH_TYPE_NOP = 24,
	SWITCH_TYPE_MOISTURE = 25,
	SWITCH_TYPE_INACTIVE = 26,
	SWITCH_TYPE_SIGN_SPLIT = 27,
	SWITCH_TYPE_ALWAYS_ON = 28,
	SWITCH_TYPE_ANIMATIC = 29,
	SWITCH_TYPE_SCORE = 30,
	SWITCH_TYPE_DEATH = 31,
	SWITCH_TYPE_CUTSCENE_CAM_FINISHED = 32,
	SWITCH_TYPE_CUTSCENE_CAM_ACTIVE = 33,
	SWITCH_TYPE_MAGIC_MOUTH = 34,
	SWITCH_TYPE_SELECTOR = 35,
	SWITCH_TYPE_MICROCHIP = 36,
	SWITCH_TYPE_CIRCUIT_BOARD = 37,
	SWITCH_TYPE_CONTROL_PAD = 38,
	SWITCH_TYPE_PROJECTILE = 39,
	SWITCH_TYPE_CIRCUIT_NODE = 40,
	SWITCH_TYPE_ANGLE = 41,
	SWITCH_TYPE_VELOCITY_LINEAR = 42,
	SWITCH_TYPE_VELOCITY_ANGULAR = 43,
	SWITCH_TYPE_MOVINATOR_PAD = 44,
	SWITCH_TYPE_MOTION_RECORDER = 45,
	SWITCH_TYPE_FILTER = 46,
	SWITCH_TYPE_COLOURGATE = 47,
	SWITCH_TYPE_WAVEGENERATOR = 48,
	SWITCH_TYPE_EMITTEE = 49,
	SWITCH_TYPE_POCKET_ITEM = 50,
	SWITCH_TYPE_POSE = 51,
	SWITCH_TYPE_ADVANCED_COUNTDOWN = 52,
	SWITCH_TYPE_STATE_SENSOR = 53,
	SWITCH_TYPE_KEY_REMOTE = 54,
	SWITCH_TYPE_VITA_PAD = 55,
	SWITCH_TYPE_TWEAK_TRIGGER = 56,
	SWITCH_TYPE_WORM_HOLE = 57,
	SWITCH_TYPE_QUEST = 58,
	SWITCH_TYPE_GRID_MOVER = 59,
	SWITCH_TYPE_QUEST_SENSOR = 60,
	SWITCH_TYPE_ADVENTURE_ITEM_GETTER = 61,
	SWITCH_TYPE_SHARDINATOR = 62,
	SWITCH_TYPE_POCKET_ITEM_DISPENSER_DEPRECATED = 63,
	SWITCH_TYPE_POCKET_ITEM_PEDESTAL = 64,
	SWITCH_TYPE_DATA_SAMPLER = 65,
	SWITCH_TYPE_TREASURE_SLOT = 66,
	SWITCH_TYPE_STREAMING_HINT = 67,
	SWITCH_TYPE_JOINT_POSITION = 68,
	SWITCH_TYPE_SLIDE = 69,
	SWITCH_TYPE_IN_OUT_MOVER = 70,
	SWITCH_TYPE_SAVE_CHIP = 71,
	SWITCH_TYPE_PLATFORM_SENSOR = 72,
	SWITCH_TYPE_RACE_END = 73,
	SWITCH_TYPE_ANTI_STREAMING = 74,
	SWITCH_TYPE_GAME_LIVE_STREAMING_CHOICE = 75,
	SWITCH_TYPE_SEARCHLIGHT = 76,
	SWITCH_TYPE_POPIT_CURSOR_SENSOR = 77,
	SWITCH_TYPE_PROGRESS_BOARD = 78,
	SWITCH_TYPE_BOUNCER = 79,
	SWITCH_TYPE_KILL_TWEAKER = 80,
	SWITCH_TYPE_POWERUP_TWEAKER = 81,
	SWITCH_TYPE_RACE_START = 82,
	SWITCH_TYPE_DECORATION_MOUNT = 83,
	SWITCH_TYPE_SPRING_SENSOR = 84,

    NUM_SWITCH_TYPES
};

class CSwitchSignal {
public:
	float Analogue;
#ifndef LBP1
	int Ternary;
	int PlayerNumber;
#endif
};

class PSwitch : public CPart {
public:
    inline int& GetType() { return *(int*)(((char*)this) + 0x4c); }
};