#ifndef RESOURCE_MACRO
    #define RESOURCE_MACRO(type, class_name, headers) class class_name;
    #define RESOURCE_MACRO_EPHEMERAL
#endif

#ifndef RESOURCE_MACRO_UNIMPLEMENTED
    #define RESOURCE_MACRO_UNIMPLEMENTED(type, class_name, headers) class class_name;
    #define RESOURCE_MACRO_UNIMPLEMENTED_EPHEMERAL
#endif

RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_TEXTURE, RTexture, NULL)
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_MESH, RMesh, "MSHbMSHt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_PIXEL_SHADER, RPixelShader, NULL)
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_VERTEX_SHADER, RVertexShader, NULL)
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_ANIM, RAnim, "ANMbANMt")
RESOURCE_MACRO(RTYPE_GUID_SUBST, RGuidSubst, "GSBbGSBt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_GFXMATERIAL, RGfxMaterial, "GMTbGMTt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SPU_ELF, RSpuElf, NULL)
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_LEVEL, RLevel, "LVLbLVLt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_FILENAME, RFilename, NULL)
RESOURCE_MACRO(RTYPE_SCRIPT, RScript, "FSHbFSHt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SETTINGS_CHARACTER, RSettingsCharacter, "CHAbCHAt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_FILE_OF_BYTES, RFileOfBytes, NULL)
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SETTINGS_SOFT_PHYS, RSettingsSoftPhys, "SSPbSSPt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_FONTFACE, RFontFace, NULL)
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_MATERIAL, RMaterial, "MATbMATt")
RESOURCE_MACRO(RTYPE_DOWNLOADABLE_CONTENT, RDLC, "DLCbDLCt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_EDITOR_SETTINGS, REditorSettings, NULL)
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_JOINT, RJoint, "JNTbJNTt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_GAME_CONSTANTS, RGameConstants, "CONbCONt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_POPPET_SETTINGS, RPoppetSettings, "POPbPOPt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_CACHED_LEVEL_DATA, RCachedLevelData, "CLDbCLDt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SYNCED_PROFILE, RSyncedProfile, "PRFbPRFt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_BEVEL, RBevel, "BEVbBEVt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_GAME, RGame, "GAMbGAMt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SETTINGS_NETWORK, RNetworkSettings, "NETbNETt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_PACKS, RPacks, "PCKbPCKt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_BIG_PROFILE, RBigProfile, "BPRbBPRt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SLOT_LIST, RSlotList, "SLTbSLTt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_TRANSLATION, RTranslationTable, NULL)
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_PARTICLE_SETTINGS, RParticleSettings, "PTSbPTSt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_LOCAL_PROFILE, RLocalProfile, "IPRbIPRtIPRe")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_LIMITS_SETTINGS, RLimitsSettings, "LMTbLMTt")
#ifndef LBP1
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_TUTORIALS, RTutorials, "TUTbTUTt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_GUID_LIST, RGuidList, "GLTbGLTt")
#else
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_PARTICLE_TEMPLATE, RParticleTemplate, "PTTbPTTt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_PARTICLE_LIBRARY, RParticleLibrary, "PTLbPTLt")
#endif

RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_AUDIO_MATERIALS, RAudioMaterials, "AUMbAUMt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SETTINGS_FLUID, RFluidSettings, "SSFbSSFt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_PLAN, RPlan, "PLNbPLNt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_TEXTURE_LIST, RTextureList, "TXLbTXLt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_MUSIC_SETTINGS, RMusicSettings, "MUSbMUSt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_MIXER_SETTINGS, RMixerSettings, "MIXbMIXt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_PALETTE, RPalette, "PALbPALt")
RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_REPLAY_CONFIG, RReplayConfig, "REPbREPt")

#ifndef LBP1
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_STATICMESH, RStaticMesh, NULL)
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_ANIMATED_TEXTURE, RAnimatedTexture, "ATXbATXt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_VOIP_RECORDING, RVoipRecording, "VOPbVOPt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_PINS, RPins, "PINbPINt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_INSTRUMENT, RInstrument, "INSbINSt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SAMPLE, RSample, NULL)
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_OUTFIT_LIST, ROutfitList, "OUTbOUTt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_PAINTBRUSH, RPaintBrush, "PBRbPBRt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_THING_RECORDING, RThingRecording, "RECbRECt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_PAINTING, RPainting, "PTGbPTGt")
#endif

#if defined(LBP3) || defined(HAS_CROSS_CONTROLLER)
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_QUEST, RQuest, "QSTbQSTt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_ANIMATION_BANK, RAnimationBank, "ABKbABKt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_ANIMATION_SET, RAnimationSet, "ASTbASTt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SKELETON_MAP, RSkeletonMap, "SMPbSMPt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SKELETON_REGISTRY, RSkeletonRegistry, "SRGbSRGt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SKELETON_ANIM_STYLES, RSkeletonAnimStyles, "SASbSASt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_CROSSPLAY_VITA, RCrossplayVita, NULL)
#endif

#ifdef LBP3
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_STREAMING_CHUNK, RStreamingChunk, "CHKbCHKt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_SHARED_ADVENTURE_DATA, RSharedAdventureData, "ADSbADSt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_ADVENTURE_PLAY_PROFILE, RAdventurePlayProfile, "ADPbADPt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_ANIMATION_MAP, RAnimationMap, "AMPbAMPt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_CACHED_COSTUME_DATA, RCachedCostumeData, "CCDbCCDt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_DATALABELS, RDataLabels, "DLAbDLAt")
    RESOURCE_MACRO_UNIMPLEMENTED(RTYPE_ADVENTURE_MAPS, RAdventureMaps, "ADMbADMt")
#endif

#ifdef RESOURCE_MACRO_EPHEMERAL
    #undef RESOURCE_MACRO
    #undef RESOURCE_MACRO_EPHEMERAL
#endif

#ifdef RESOURCE_MACRO_UNIMPLEMENTED_EPHEMERAL
    #undef RESOURCE_MACRO_UNIMPLEMENTED
    #undef RESOURCE_MACRO_UNIMPLEMENTED_EPHEMERAL
#endif
