#pragma once

enum EResourceLoadState
{
    LOAD_STATE_UNLOADED,
    LOAD_STATE_LOADING_DATA,
    LOAD_STATE_PENDING_DESERIALISE,
#ifndef LBP1
    LOAD_STATE_DESERIALISING,
#endif
    LOAD_STATE_LOADED,
#ifndef LBP1
    LOAD_STATE_LOADED_SERIALISING,
#endif
    LOAD_STATE_ERROR,
    LOAD_STATE_ERROR_BADHASH,
    LOAD_STATE_ERROR_FILENOTFOUND,
#ifdef LBP1
    LOAD_STATE_ERROR_FAILED_LOAD_BLURAY,
    LOAD_STATE_ERROR_FAILED_HASH_COMPARE,
#endif
    LOAD_STATE_ERROR_NO_DATA_SOURCE,
#ifndef LBP1
    LOAD_STATE_ERROR_MODERATED
#endif
};

enum ESerialisationMode
{
    MODE_SAVE,
    MODE_LOAD
};

enum ESerialisationType
{
    PREFER_BINARY,
    PREFER_TEXT,
    PREFER_FILE,
    PREFER_DEFAULT,
    PREFER_ENCRYPTED
};

enum EWaitForStreamingResources
{
    WAIT_FOR_STREAMING_RESOURCES,
    DONT_WAIT_FOR_STREAMING_RESOURCES
};
