#pragma once

enum ESlotType {
    LEVEL_TYPE_DEVELOPER_CREATED,
    LEVEL_TYPE_USER_CREATED_ON_SERVER,
    LEVEL_TYPE_USER_CREATED_STORED_LOCALLY,
    LEVEL_TYPE_LOCAL_GROUP,
    LEVEL_TYPE_DEVELOPER_GROUP,
    LEVEL_TYPE_POD,
    LEVEL_TYPE_FAKE,
    LEVEL_TYPE_REMOTE_MOON,
    LEVEL_TYPE_DLC_LEVEL,
    LEVEL_TYPE_DLC_PACK,
    LEVEL_TYPE_PLAYLIST,
#ifdef LBP3
    LEVEL_TYPE_ADVENTURE_LEVEL_DEVELOPER,
    LEVEL_TYPE_ADVENTURE_PLANET_DEVELOPER,
	LEVEL_TYPE_ADVENTURE_AREA_DEVELOPER,
	LEVEL_TYPE_ADVENTURE_PLANET_USER_PUBLISHED,
	LEVEL_TYPE_ADVENTURE_PLANET_USER_LOCAL,
	LEVEL_TYPE_ADVENTURE_LEVEL_USER,
	LEVEL_TYPE_ADVENTURE_AREA_USER,
	LEVEL_TYPE_ADVENTURE_PLANET_REMOTE_MOON,
#endif
    LEVEL_TYPE_MAX
};
